export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export type LOGIN_USER_SUCCESS = typeof  LOGIN_USER_SUCCESS;

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export type LOGOUT_USER_SUCCESS = typeof LOGOUT_USER_SUCCESS;

export const PROFILE_DELETE_SUCCESS = "PROFILE_DELETE_SUCCESS";
export type PROFILE_DELETE_SUCCESS = typeof PROFILE_DELETE_SUCCESS;

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export type UPDATE_PROFILE_SUCCESS = typeof UPDATE_PROFILE_SUCCESS;

export const UPDATED_ROOM_LIST = "UPDATED_ROOM_LIST";
export type UPDATED_ROOM_LIST = typeof UPDATED_ROOM_LIST;

export const UPDATED_FRIEND_LIST = "UPDATED_FRIEND_LIST";
export type UPDATED_FRIEND_LIST = typeof UPDATED_FRIEND_LIST;

export const CHANGE_CURRENT_ROOM = "CHANGE_CURRENT_ROOM";
export type CHANGE_CURRENT_ROOM = typeof CHANGE_CURRENT_ROOM;